### ISSUE TITLE
Command books

### ISSUE THREAD

**Issue by adrian7zai** [tanjeffreyz/auto-maple-resources#13]
Any other classes/jobs' command books?

**Comment by Tsukino-uwu** [comment]
I have done Adele & Shadower so far, I might make 2 generic teleport & flashjump command books that just work for all pre lvl200 classes as i don't think it requires as much effort put into it while just lvling up compared to lvl200+ grinding/farming where you probly want to use all of a classes kit more~

if you want to make for another specific class that don't have a command book yet you could try editing and using kanna for mage/teleport classes or the shadower for melee/range flashjump classes as a base. just take a look at the command books with notepad++ and rename things/move things around a bit and hopefully it shouldn't be to complicated to understand , and if you uploaded/push/share it here at [auto-maple-resources](https://github.com/tanjeffreyz/auto-maple-resources) other people can download/use them as well. Not a lot of people that are sharing/making command books or routines yet

**Comment by LiliaTheSuccubus** [comment]
edit: after commenting, i see that the issue remains closed (i thought it would be like bumping a topic on a forum, and reopen the issue). i can repost this into a separate issue or someplace else more fitting if needed. but i'll just wait for a response for now (a couple of days, until I figure it's not being seen).

Sorry for reopening this as I'm new to coding and GitHub and might not know if what I'm doing is "poor etiquette".
I just wanted to mention I'm working on several handbooks as I'm trying to use this as an opportunity to learn Python.
Auto Maple is one of the main reasons I started trying to learn how to code in June 2023.

I originally forked from Jeff's repo, but because I was editing both the resources + main bot code (reducing delays and adding rune behavior/changing notifier settings), sometimes it would overwrite my resource changes, and since I'm still new to this, I didn't know how to handle this. When I tried to just delete the git files, it just ended up breaking since I didn't really know what I was doing. I managed to do it this morning, but I know that any of my commits will not be linked to the community resource, and I'd like to know if there's a way to link them together so that my commits to my own repo will also be able to be accessed from the community repo, without having to copy and paste my files onto a clone of a forked community repo and essentially commiting things twice.

This is my current workspace:
![chrome_1TatoIsO90](https://github.com/tanjeffreyz/auto-maple-resources/assets/137910156/28c62262-ca62-4888-8529-2ec480ff255c)


And I'd like to know how I can add my resources to the community resources so that I can make pull requests for my completed work. This is what my resources look like for now:
![chrome_NvkDsn9rLS](https://github.com/tanjeffreyz/auto-maple-resources/assets/137910156/607b7f34-1ddb-4a50-a1de-08075567fef1)

I'm also worried about committing an unfinished or buggy commandbook/layout, so I've done most of my work offline. I'd love to also know the solution to that (I assume you can just hold off on making a pull request until it's ready, but GitHub Desktop makes it such a huge blue button that I can't resist clicking on it and pushing my changes to main even when I make the smallest change, like renaming a function.)

**Comment by bercouli3** [comment]
> edit: after commenting, i see that the issue remains closed (i thought it would be like bumping a topic on a forum, and reopen the issue). i can repost this into a separate issue or someplace else more fitting if needed. but i'll just wait for a response for now (a couple of days, until I figure it's not being seen).
> 
> Sorry for reopening this as I'm new to coding and GitHub and might not know if what I'm doing is "poor etiquette". I just wanted to mention I'm working on several handbooks as I'm trying to use this as an opportunity to learn Python. Auto Maple is one of the main reasons I started trying to learn how to code in June 2023.
> 
> I originally forked from Jeff's repo, but because I was editing both the resources + main bot code (reducing delays and adding rune behavior/changing notifier settings), sometimes it would overwrite my resource changes, and since I'm still new to this, I didn't know how to handle this. When I tried to just delete the git files, it just ended up breaking since I didn't really know what I was doing. I managed to do it this morning, but I know that any of my commits will not be linked to the community resource, and I'd like to know if there's a way to link them together so that my commits to my own repo will also be able to be accessed from the community repo, without having to copy and paste my files onto a clone of a forked community repo and essentially commiting things twice.
> 
> This is my current workspace: ![chrome_1TatoIsO90](https://user-images.githubusercontent.com/137910156/258597307-28c62262-ca62-4888-8529-2ec480ff255c.png)
> 
> And I'd like to know how I can add my resources to the community resources so that I can make pull requests for my completed work. This is what my resources look like for now: ![chrome_NvkDsn9rLS](https://user-images.githubusercontent.com/137910156/258597319-607b7f34-1ddb-4a50-a1de-08075567fef1.png)
> 
> I'm also worried about committing an unfinished or buggy commandbook/layout, so I've done most of my work offline. I'd love to also know the solution to that (I assume you can just hold off on making a pull request until it's ready, but GitHub Desktop makes it such a huge blue button that I can't resist clicking on it and pushing my changes to main even when I make the smallest change, like renaming a function.)

Pls share the command book and routine for demon slayer! A Google drive link to allow download would be nice

**Comment by LiliaTheSuccubus** [comment]
> Pls share the command book and routine for demon slayer! A Google drive link to allow download would be nice

It's just a placeholder, sorry. I don't have a Demon Slayer bot set up since it's just a keyweighting class. I justadded in beginner upjump logic to the command book since someone had written it in a previous issue.
